- General/CoolSnippets.md
> Add a code snippet on how to dowload a file with a progress bar

- General/Baselines.md
Added comment about the fact that the baseline class should be in a separated packageIt was unclear.
> Added content about baseline's package.

- PharoProjects/DynamicVariables.md
> Update DynamicVariables.md | Typo on "variables"

- Migration/MigrationToPharo7.md
- README.md
> add migration guideline from Pharo 6.1 to Pharo 7.0

- General/Traits.md
So we will be able to remove the "review" badge :-)
> Reviewing page on Traits

- README.md
> Update README.md's TOC

- General/InterestingsToKnowForBeginners.md
Written section "Valuables (Blocks and Symbols)"
> Added content for valuables

- General/InterestingsToKnowForBeginners.md
Related to issues #3 and #18 but does not solve them entirely.
> Added some contents for Flags and pragmas.

- General/Traits.md
- Reject some instance variables received from the trait
- Alias some instance variables received from the trait
> Added documentation about inst. vars. management

- README.md
I added issues for entries to redo,
I removed ESC/P because it is really really specific no need for a dedicated page.
> Removed links to page that are not done yet.

- PharoProjects/DynamicVariables.md
> Fixed inconsistency with "dynamic variable"

- General/CoolSnippets.md
Also added a TOC.
Fix issue #84.
> Added example of code transformation.

- General/CoolSnippets.md
Fix issue #37.
Still need to regenerate TOC. Waiting for PR #95 to be integrated.
> Added code snippet to browse available icons

- General/DeployYourPharoApplication.md
remove unnecessary tab spaces and fix smalltalk highlighting
> remove unnecessary tab spaces and fix smalltalk highlighting

- General/CoolSnippets.md
I removed unnecessary tab spaces in a block of code
> Remove unnecessary tab spaces

- MANIFEST.md
Hopefully it's an ecosystem that thrives and grows, not an echosystem that just reflects back and forth. :-)
> MANIFEST.md typo

- General/Baselines.md
I moved the TODO into #107 issue.
> Moved TODO into an issue.

- CONTRIBUTION.md
Added the rule.
Fixed the exemple under to use tabulation as well ;-).
> Added rule on source code formatting

- PharoProjects/RichText.md
> Transforms spaces to tabs

- PharoProjects/WebBrowser.md
I do not think the code should begin with two spaces if there is only one line  ?
> Remove useless spaces

- ExternalProjects/Export/JSON.md
Transforms spaces to tabs
&
fix one ident
see #111
> Transforms spaces to tabs & fix one ident

- General/Baselines.md
transforms spaces to tabs and 
I remove some ending '.' because in most of this page, the line doesn't end with it (in pharo code)
> transforms spaces to tabs and remove ending '.'

- General/Extensions.md
Remove two useless spaces and transforms spaces to tabs
> Remove two useless spaces and transforms spaces to tabs

- General/CoolSnippets.md
> Add script to rename methods programatically

- PharoProjects/DynamicVariables.md
I am not sure of what the quoted text at the beginning tries to explain.
Maybe you can develop @jecisc ?
> Did a pass.

- ExternalProjects/Export/CSV.md
It is more intention revealing to use #writeHeader:
> Use #writeHeader:

- General/MenuBar.md
- README.md
> Add page on Menubar and World menu

- General/CodingConventions.md
- README.md
This is a WIP but I don't have the time to write it all in one go. We should integrate it and iterate on it.
> Init coding conventions

- General/Extensions.md
> Add note en variables

- General/Baselines.md
> Add info on #includes:

- README.md
And sorted Pharo projects entries.
> Added Announcer entry

- General/Traits.md
> Fixed traits page

- General/CoolSnippets.md
> Add how to find dependencies on a package

- General/InterestingsToKnowForBeginners.md
> Added explanation about debuggerCompleteToSender pragma

- General/SortingCollections.md
- README.md
> Add page on sorting

- PharoProjects/RichText.md
I added some stuff on the rich test section under projects.
> Expanded on RichText.md

- PharoProjects/RichText.md
I added a section in RichText.md showing how to inline images in Text.
> added section on inline images to RichText.md

- README.md
as the page contains no todo and it seems to be complete.
> Removed unfinished tag from CJKCharacter

- General/CodingConventions.md
- README.md
Removed protocol convention section TODO and opened an issue for this task.
> Cleaned and fixed coding conventions page

- General/Profiling.md
- README.md
An issue has been created for that #232
> Removed TODO as it was moved to an issue.

- README.md
> Added CC BY badges.

- General/Glossary.md
> Replace titles by bold

- General/DeployYourPharoApplication.md
- README.md
and created related issue #252
> Removed todo section

- General/Glossary.md
And fixes a minor issue in Binary message def.
> Added definition for bootstrap

- General/Glossary.md
Link to bootstrapper repository added to Bootstrap definition
> Adding link to bootstrapper repository

- General/Baselines.md
Feedback from repeter#7231 on discord.
> Clarify projectClass method contents

- README.md
- Added missing '-'
- Removed `(external link)` as all links in this section are external.
> Minor fixes.

- General/SortingCollections.md
> Update sorting documentation to Pharo 8

- CONTRIBUTION.md
> Update unfinished pages management

- General/Windows10SubsystemForLinux.md
> Removed dead link

- General/TweakingBigImages.md
- README.md
> Tweaking Big Images

- ExternalResources/Community.md
> Added sebastiansastre blog.

- General/MustKnowForBeginners.md
> Add doc on more shortcuts

- General/HowToRunPharoFromCommandLine.md
> Fix typo in HowToRunPharoFromCommandLine.md

- General/GithubActions.md
> Review/update  GHA documentation

- General/GithubActions.md
Hello
I updated my personal website and discovered incorrect link from the documentation so I updated the links.
Thanks for your work!
> Update URL to badetitou.fr blogpost (as reference)

- General/ExportFormats.md
Improves the instructions for updating the tonel format
> Update ExportFormats.md for improved update instructions
